name: GPT Apply Changes

on:
  issue_comment:
    types: [created]

jobs:
  apply:
    if: startsWith(github.event.comment.body, '/apply ')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install openai@4.0.0

      - name: Run GPT Apply Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/workflows/scripts/gpt-apply.mjs "${{ github.event.comment.body }}"
